---
# install MongoDB

# Mongo ppa key
- name: Add mongo ppa key
  apt_key:
    keyserver: "{{ keyserver_mongo }}"
    id: "{{ id_mongo_repo }}"
    state: present

# Mongo Sources list
- name: Add mongo sources list
  lineinfile: # Search the line on mongodb.list
    line: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    dest: /etc/apt/sources.list.d/mongodb.list
    state: present
    create: yes


# Install MongoDB package
#- name: Install MongoDB
#  apt:
#    name=mongodb-org
#    state=latest