---
# install MongoDB

# Mongo ppa key
- name: Add mongo ppa key
  apt_key:
    url: "{{ keyserver_mongo }}"
    id: "{{ id_mongo_repo }}"
    state: present

- name: MongoDB -- Install ppa
  apt_repository:
    repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' 
    state: present

# Install Docker package
- name: install docker
  package:
    name: "mongodb-org"
    state: present

#- name: Ensure MongoDB is running
#  service:
#    name: mongod
#    state: started