---

- name: VM Aprovisioning
  hosts: usvm
  remote_user: us

  roles:
    - us.apache # Rol de Apache
    - us.install_docker # Rol de instalacion Docker
    - us.install_mongodb # Rol de instalacion de MongoDB

  vars_files:
    - ~/Escritorio/ansible_vm/vars/vm_vars.yml
