---

- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600


- name: PHP | Install required software
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - php-mysql
    - php
    - libapache2-mod-php
    - php-mcrypt

# install PHP extension
- name: PHP | Install PHP extension
  apt: 
    name: php-gd
    state: present

#- name: PHP | install packages
#  package:
#    name: "{{ php_package }}"
#    state: installed

# Restart PHP Service
# name: PHP | enable service
#  service:
#    name: apache2
#    state: started