---
# install Apache2

- name: Apache | install packages
  package:
    name: "{{ web_package }}"
    state: installed

# Restart Apache Service
- name: Apache | enable service
  service:
    name: apache2
    state: started