---
# install Docker

# Install dependencies of Docker
- name: Docker | Install dependencies
  apt: 
    name={{ item }}
    # update_cache=yes
  with_items: 
    - python-dev
    - python-setuptools

# Install pip
- name: Docker | Install pip
  easy_install:
      name: pip

# Install Docker py
- name: Docker | Install docker-py
  pip: 
      name=docker-py 
      state=present
      version={{ docker_py_version }}

# Add Docker apt repo
- name: Docker | Add docker apt repo
  apt_repository:
      repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
      state: present
  when: ansible_os_family == "Debian"

# Add Docker apt repo
# - name: Docker | Add yum repo
#  yum_repository:
#      repo: 'https://yum.dockerproject.org/repo/main/centos/7/'
#      state: present
#  when: ansible_os_family == "CentOS"

# Import the Docker repository key Debian
#- name: Import the Docker repository key
#  apt_key:
#      url: "{{ url_docker_project_debian }}"
#      state: present
#      id: "{{ id_docker_repo }}"


#     "{{ url_docker_project_yum }}"

# Install Docker package
- name: Docker | install docker
  package:
    name: "{{ docker_package }}"
    state: installed

#  Start Docker Service
- name: Docker | start service
  service:
    name: docker
    state: started