---

#- name: Update apt cache
#  apt: update_cache=yes cache_valid_time=3600

# Download Wordpress
- name: Wordpress | Donwload Wordpress
  get_url:
    url: "{{ url_wordpress }}" 
    dest: "{{ wordpress_tmp }}"
    validate_certs: no

# Extract wordpress
- name: Wordpress | Extract
  unarchive: 
    src: "{{ wordpress_tmp }}"
    dest: "{{ wordpress_dest }}"
    copy: no

# Update default Apache site
- name: Wordpress | Update Apache site
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

# Copy sample config file
- name: Wordpress | Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

# Update Wordpress config file
- name: Wordpress | Update config file
  lineinfile:
    dest: "{{ wp_php_config_dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}